### ISSUE TITLE
Disparadores

### ISSUE THREAD

**Issue by DanielGilB** [guilogar/proyecto_abd#4]
Crear 2 disparadores.

**Comment by DanielGilB** [comment]
Crear 2 disparadores más.

Total 4.

**Comment by DanielGilB** [comment]
Uno de los disparadores sea el que controle el stock negativo, por si se intenta comprar un producto con 0 stock no te deje o algo.

**Comment by Asega1996** [comment]
//Muestra las ganancias totales del videoclub en la variable @sum
CREATE TRIGGER ganancias_totales BEFORE INSERT ON orders_price FOR EACH ROW
SET
  @sum = @sum + NEW.price;

**Comment by Asega1996** [comment]
/*Al updatear un producto, comprueba antes que su precio debe de ser positivo para mantener la consistencia*/
CREATE TRIGGER update_products BEFORE UPDATE ON products
    FOR EACH ROW
    BEGIN
         IF NEW.price< 0 THEN
             SET NEW.price= ABS(NEW.price);
         END IF;
    END;

**Comment by Asega1996** [comment]
/* Nos ayuda a asegurar que el stock nunca será negativo y que la bbdd quede inconsistente*/
CREATE TRIGGER check_stock BEFORE UPDATE ON products
FOR EACH ROW
BEGIN
IF NEW.stock< 0 THEN
SET NEW.stock= 0;
END IF;
END;

**Comment by Asega1996** [comment]
/*Calcularemos la nueva cantidad de gastos referentes a los empleados en la variable @gastos cada vez que se inserte un nuevo registro*/
CREATE TRIGGER gastos_totales 
AFTER INSERT ON salaries
FOR EACH ROW
SET
@gastos = @gastos+ NEW.amount;
