### ISSUE TITLE
Interacciones

### ISSUE THREAD

**Issue by DanielGilB** [guilogar/proyecto_abd#9]
Indicar al menos 2 interacciones con agentes

**Comment by Asega1996** [comment]
Interacciones con agentes:

1) Interacción con desarrolladores de la página web del videoclub: Como administradores de la base de datos deberíamos poder proporcionarle a dichos desarrolladores un usuario capaz de poder observar todas las tablas necesarias, exceptuando las de trabajadores ya que contienen información sensible y teniendo el usuario anteriormente mencionado únicamente permisos de lectura, ya que las inserciones de nuevos clientes/productos se realizarán de forma presencial en el videoclub.

2) Interacción con proveedores: A los proveedores se le podría proporcionar un usuario con acceso a la vista de productos_proveedores existente en la web para comprobar si el videoclub ya ofrece un producto que un proveedor quiera poner a la venta en nuestro establecimiento.
